In [1]:
import numpy as np
import pandas as pd
import itertools

In [26]:
class Perceptron:
    def __init__(self, x_input, weights):

        self.x_input = x_input
        self.weights = weights
        

    def weighted_sum(self):
        total = 0
        for i in range(len(self.weights)):
            total += self.x_input[i] * self.weights[i]
        
        return total

    def simple_perceptron(self, threshold):
        
        total = self.weighted_sum() 
        if (total >= threshold):
            return 1
        else:
            return 0
    
    def step_perceptron(self, bias):
        
        total = self.weighted_sum() + bias
        if (total >= 0):
            return 1
        else:
            return 0

    


In [3]:
x_input = [1, 0, 1] 
weights = [7, 4, 2]     
threshold = 8         


perceptron = Perceptron(x_input, weights)
output = perceptron.simple_perceptron(threshold)

print("Perceptron Output:", output)

Perceptron Output: 1


In [4]:

binary_inputs = list(itertools.product([0, 1], repeat=3))
binary_inputs


[(0, 0, 0),
 (0, 0, 1),
 (0, 1, 0),
 (0, 1, 1),
 (1, 0, 0),
 (1, 0, 1),
 (1, 1, 0),
 (1, 1, 1)]

In [5]:
def categorize_input(bin_tuple):
 
    bit1, bit2, bit3 = bin_tuple
    cat1 = "Black" if bit1 == 1 else "Not Black"
    cat2 = "Full" if bit2 == 1 else "Half"
    cat3 = "Cotton" if bit3 == 1 else "Not cotton"
    return (cat1, cat2, cat3)


binary_inputs = list(itertools.product([0, 1], repeat=3))
categorized_inputs = [categorize_input(bits) for bits in binary_inputs]

data = pd.DataFrame(categorized_inputs, columns=["Color", "Sleeve", "Fabric"])

weights = [7, 4, 2]     
threshold = 8  
category_output = []

for binary in binary_inputs:
    perceptron = Perceptron(binary, weights)
    output = perceptron.simple_perceptron(threshold)
    category_output.append("Buys" if output == 1 else "Not buys")

In [6]:
data["Buys?"] = category_output
data

Color Sleeve      Fabric     Buys?
0  Not Black   Half  Not cotton  Not buys
1  Not Black   Half      Cotton  Not buys
2  Not Black   Full  Not cotton  Not buys
3  Not Black   Full      Cotton  Not buys
4      Black   Half  Not cotton  Not buys
5      Black   Half      Cotton      Buys
6      Black   Full  Not cotton      Buys
7      Black   Full      Cotton      Buys

# MLP

In [7]:
input_2 = list(itertools.product([0, 1], repeat=2))
input_1 = [1, 0]
weights_1 = [1, 1]
weights_2 = [1, 1]
weights_3 = [-1, 1]
bias_1 = -1.5
bias_2 = -0.5
bias_3 = -0.5

perceptron_1 = Perceptron(input_1, weights_1)
perceptron_1_output = perceptron_1.step_perceptron(bias_1)

perceptron_2 = Perceptron(input_1, weights_2)
perceptron_2_output = perceptron_2.step_perceptron(bias_2)

input_final_perceptron = [perceptron_1_output, perceptron_2_output]
perceptron_3 = Perceptron(input_final_perceptron, weights_3)
perceptron_3_output = perceptron_3.step_perceptron(bias_3)

perceptron_3_output

1

In [13]:
input_2 = list(itertools.product([0, 1], repeat=2))
weights_1 = [1, 1]
weights_2 = [1, 1]
weights_3 = [-1, 1]
bias_1 = -1.5
bias_2 = 0.5
bias_3 = -0.5

for input_1 in input_2:
    perceptron_1 = Perceptron(input_1, weights_1)
    perceptron_1_output = perceptron_1.step_perceptron(bias_1)
    
    perceptron_2 = Perceptron(input_1, weights_2)
    perceptron_2_output = perceptron_2.step_perceptron(bias_2)
    
    input_final_perceptron = [perceptron_1_output, perceptron_2_output]
    perceptron_3 = Perceptron(input_final_perceptron, weights_3)
    perceptron_3_output = perceptron_3.step_perceptron(bias_3)
    
    print("Input:", input_1, "Output:", perceptron_3_output)

Input: (0, 0) Output: 1
Input: (0, 1) Output: 1
Input: (1, 0) Output: 1
Input: (1, 1) Output: 0


In [9]:
x_inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
x_inputs.shape[0]

4

In [15]:
x_inputs[1]

array([0, 1])

In [6]:
input_2 = np.array(list(itertools.product([0, 1], repeat=2)))
input_2.shape[1]

2

In [7]:
input_2

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

# Backpropagation

In [30]:
class BackPropagation:

    def __init__ (self, x_input, y_output, learning_rate = 0.1, max_iters = 100):
        self.x_input = x_input
        self.y_output = y_output
        self.learning_rate = learning_rate
        self.max_iters = max_iters
        self.num_inputs = x_input.shape[1]
        self.length_inputs = x_input.shape[0]



    def weights_bias (self):
        weights = np.random.rand(self.num_inputs)
        bias = 0
        
        for iters in range(self.max_iters):
            for i in range(self.length_inputs):
                
                output = self.step_perceptron(self.x_input[i], weights, bias)
                
                error = (self.y_output[i] - output)
                
                weights = weights + (self.learning_rate * error *self.x_input[i])
                bias = bias + (self.learning_rate * error)
        
        return weights, bias

    
    def step_perceptron(self, inputs, weights, bias):
        total = 0
        for i in range(len(weights)):
            total += inputs[i] * weights[i]
        total += bias
        
        if (total >= 0):
            return 1
        else:
            return 0


In [31]:
x_input = np.array([[0,0],[0,1],[1,0],[1,1]])
y_output = np.array([0,1,1,1])
learning_rate = 0.1
max_iters = 100

my_perceptron = BackPropagation(x_input, y_output, learning_rate, max_iters)
weights, bias = my_perceptron.weights_bias()

In [32]:
weights

array([0.40355934, 0.31509514])

In [33]:
bias

-0.1

In [34]:
for input_test in x_inputs:
    test_perceptron = Perceptron(input_test, weights)
    output_test = test_perceptron.step_perceptron(bias)
    print("Input:", input_test, "Output:", output_test)
    


Input: [0 0] Output: 0
Input: [0 1] Output: 1
Input: [1 0] Output: 1
Input: [1 1] Output: 1


In [1]:
from sklearn.model_selection import train_test_split as tts
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

import warnings
warnings.filterwarnings("ignore")

In [7]:

import pandas as pd
data = pd.read_csv("used_car_clean.csv")
#x_ind = data[['year', 'Mileage']]
#X = data[['year', 'Mileage']]
X = data[['Mileage', 'horsepower','year']]
#X = data[['body_condition', 'mechanical_condition', 'no_of_cylinders', 
#'horsepower', 'year', 'Mileage']]
#X= x_ind.values
#y = data['Price_USD'].values
y = data['Price_USD']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define and train the MLPRegressor model
# 'adam' stands for Adaptive Moment Estimation. 
#It’s an extension of stochastic gradient descent that adapts learning rates for each parameter 
#using estimates of first and second moments of the gradients.
mlp_regressor = MLPRegressor(hidden_layer_sizes=(64,32,16), activation='relu', 
                             solver='adam', random_state=42)
mlp_regressor.fit(X_train_scaled, y_train)

# Calculate R-squared on training data
print(mlp_regressor.score(X_train_scaled,y_train))


# Make predictions on training data
train_predictions = mlp_regressor.predict(X_train_scaled)

0.5603667327065467


In [4]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [5]:
data = pd.read_csv("diabetes.csv")
col = 'Outcome'
x_ind = data.loc[:, data.columns!=col]
y_dep = data[col]

X_train, X_test, y_train, y_test = tts((x_ind),(y_dep),test_size = 0.2)
mlp = MLPClassifier(hidden_layer_sizes=(200,50), max_iter=1000)

# Train the model
mlp.fit(X_train, y_train)

# Predict on the test data
y_pred = mlp.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(confusion)    
print("Accuracy:", round(accuracy,2))
print("Precision:", round(precision,2))
print("Recall: {:.2f}".format(recall))
print("F1 Score: {:.2f}".format(f1))

Confusion Matrix:
[[75 31]
 [17 31]]
Accuracy: 0.69
Precision: 0.5
Recall: 0.65
F1 Score: 0.56
